### ISSUE TITLE
Get random enabled conflict - is missing one transition when selecting out of possible

### ISSUE THREAD

**Issue by malteschilling** [sarahtattersall/PIPECore#8]
When multiple transitions can be fired (I tested for choice, conflict: one place goes out to two transitions), always one transition is ignored and never fired (no matter how often you repeat).

Problem is: in PetriNetAnimator.java (in pipe.animation) in getRandomEnabledTransition the correct index is produced - but this is in [0, number_possible_fired_transitions - 1], but the for loop used for getting to the transition at that specific index starts at 1 - therefore it can never reach the last element of the Collection of fire-able transitions (line 80, should be corrected to for (int i = 0; i < index; i++) )

**Comment by sjdayday** [comment]
Hi Malte,

Thanks for the detail on this issue.  I'll look at it next week, and should have it fixed by 3/13.

regards,
Steve

**Comment by sjdayday** [comment]
Fixed in hierarchical nets branch, pull #12.

**Comment by sjdayday** [comment]
Fixed in master (pull #13)
